spring:
  jackson:
    time-zone: GMT+8
  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ant-path-matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.178.192.115:3306/springboot?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: springboot
    password: cwlsld
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false

  devtools:
    restart:
      enabled: false  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**  #排除文件(不重启项目)
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

  redis:
    host: 175.178.192.115
    port: 6379
    password: cwlsld
    database: 0

mybatis-plus:
  mapper-locations: classpath:com/Mapper/xml/*.xml
  type-aliases-package: com.User
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
server:
  port: 8088
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

